version: "3"
services:
    es01:
        image: "elasticsearch:7.7.1"
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - cluster.initial_master_nodes=es01
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
            - data01:/usr/share/elasticsearch/data
        ulimits:
            memlock: 
                soft: -1
                hard: -1
        ports: 
            - "9200:9200"
    gosearch:
        build: .
        environment:
            - ELASTICSEARCH_URL=http://es01:9200/
        ports:
            - "8888:8888"

volumes:
    data01:
        driver: local